export const PurchaseJoruney = {
    CategoriesNavButton: "[data-test='nav-categories']",
    PowerTools: "[data-test='nav-power-tools']",
    HandTools: "[data-test='nav-hand-tools']",
    SpecialTools: "[data-test= 'nav-special-tools']",
    OtherListItem: "[data-test= 'nav-other']",
    IncreaseQuantity: "[data-test='increase-quantity']",
    DecreaseQuantity: "[data-test='decrease-quantity']",
    UnitPrice: "[data-test= 'unit-price']",
    Quantity: "[data-test='quantity']",
    AddToCart: "[data-test='add-to-cart']",
    CartNavButton: "[data-test='nav-cart']",
    TotalPrice: "[data-test='cart-total']",
    ProceedButton: "[data-test='proceed-1']",
    SecondProceedButton: "[data-test='proceed-2-guest']",
    GuestEmail: "[data-test='guest-email']",
    GuestFirstName: "[data-test='guest-first-name']",
    GuestLastName: "[data-test='guest-last-name']",
    GuestSubmit: "[data-test='guest-submit']",
    PaymentMethod: "[data-test='payment-method']",
    ProductPageQuantity: "[data-test='product-quantity']",
    CreditCardNumber: "[data-test='credit_card_number']",
    CreditCardExpirey: "[data-test='expiration_date']",
    CreditCardCVV: "[data-test='cvv']",
    CreditCardName: "[data-test='card_holder_name']",

}